name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install Monogame
        run: dotnet new --install MonoGame.Templates.CSharp
      - run: dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
      - uses: actions/upload-artifact@v3
        with:
          name: windows build
          path: bin/Release/net6.0/win-x64/publish/
          retention-days: 5
      - run: dotnet publish -c Release -r osx-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
      - uses: actions/upload-artifact@v3
        with:
          name: mac build
          path: bin/Release/net6.0/win-x64/publish/
          retention-days: 5

         